title: minima
author: chandan
email: chandan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello world i am your host, let me know how can i help you.

# social links
github_username:  readbetweenthelines # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
